### ISSUE TITLE
ROS 2 CLI is slow

### ISSUE THREAD

**Issue by Ryanf55** [ros/meta-ros#1094]
**Describe the bug**

Every ROS 2 CLI command is much slower when using qemux86-64 with meta-ros than something like Ubuntu 22 native. It can take 10-20 seconds for some commands. I see about 5 seconds for `ros2 -h` even on my super powerful desktop. 

**To Reproduce**

Repos:
```yaml
repositories:
  poky:
    type: git
    url: git://git.yoctoproject.org/poky
    version: kirkstone
  meta-openembedded:
    type: git
    url: https://git.openembedded.org/meta-openembedded
    version: kirkstone
  meta-ros:
    type: git
    url: https://github.com/ros/meta-ros.git
    # TODO switch to kirkstone once kirkstone-next is merged
    version: kirkstone-next
```
Hashes
```bash
$ vcs custom --args rev-parse --short HEAD
/usr/bin/vcs:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
...
=== ./meta-openembedded (git) ===
730e44900
=== ./meta-ros (git) ===
685215f98
=== ./poky (git) ===
426dfdc8d2
```

1. Build `ros-image-core` 
1. `runqemu qemux86-64 ros-image-core-humble`
1. Login with `root` username
1. `time ros2 --help`

![image](https://github.com/ros/meta-ros/assets/25047695/bf18b932-53f8-41e9-b365-4c21d9e63556)

**Expected behavior**

ROS2 CLI is normally much faster. Here's the same test on host OS:
![image](https://github.com/ros/meta-ros/assets/25047695/33e699d9-58fb-4658-ad80-a16bdac9d061)
