### ISSUE TITLE
Flashing ros-image-core-humble hangs for jetson-orin-nano-devkit

### ISSUE THREAD

**Issue by jinchenglee** [ros/meta-ros#1160]
Host: x86_64 installed Ubuntu 20.04LTS
```$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

Following the directions on [kas build page](https://github.com/ros/meta-ros/tree/build/kas) has successfully built the images. 
```
git clone -b build https://github.com/ros/meta-ros
mkdir $PROJECT_DIR
KAS_WORK_DIR=$PROJECT_DIR
kas build meta-ros/kas/oeros-kirkstone-humble-jetson-orin-nano-devkit.yml
```

The image directory:
```
# /work/yocto-meta-ros/build/tmp-glibc/deploy/images/jetson-orin-nano-devkit$ pwd
/work/yocto-meta-ros/build/tmp-glibc/deploy/images/jetson-orin-nano-devkit
# /work/yocto-meta-ros/build/tmp-glibc/deploy/images/jetson-orin-nano-devkit$ ls
Image
Image--5.10.192+git0+db857ecdbe-r0-jetson-orin-nano-devkit-20240523185806.bin
Image.gz
Image.gz--5.10.192+git0+db857ecdbe-r0-jetson-orin-nano-devkit-20240523185806.bin
Image.gz-jetson-orin-nano-devkit.bin
Image-jetson-orin-nano-devkit.bin
L4TConfiguration.dtbo
L4TConfiguration-rcmboot.dtbo
modules--5.10.192+git0+db857ecdbe-r0-jetson-orin-nano-devkit-20240523185806.tgz
modules-jetson-orin-nano-devkit.tgz
ros-image-core-humble-jetson-orin-nano-devkit-20240523185806.rootfs.ext4
ros-image-core-humble-jetson-orin-nano-devkit-20240523185806.rootfs.manifest
ros-image-core-humble-jetson-orin-nano-devkit-20240523185806.tegraflash.tar.gz
ros-image-core-humble-jetson-orin-nano-devkit-20240523185806.testdata.json
ros-image-core-humble-jetson-orin-nano-devkit.ext4
ros-image-core-humble-jetson-orin-nano-devkit.manifest
ros-image-core-humble-jetson-orin-nano-devkit.tegraflash.tar.gz
ros-image-core-humble-jetson-orin-nano-devkit.testdata.json
tegra234-p3767-0003-p3768-0000-a0--5.10.192+git0+db857ecdbe-r0-jetson-orin-nano-devkit-20240523185806.dtb
tegra234-p3767-0003-p3768-0000-a0--5.10.192+git0+db857ecdbe-r0-jetson-orin-nano-devkit-20240523185806.dtb.signed
tegra234-p3767-0003-p3768-0000-a0.dtb
tegra234-p3767-0003-p3768-0000-a0.dtb.signed
tegra234-p3767-0003-p3768-0000-a0-jetson-orin-nano-devkit.dtb
tegra234-p3767-0003-p3768-0000-a0-jetson-orin-nano-devkit.dtb.signed
tegra234-p3767-overlay.dtbo
tegra234-p3768-overlay.dtbo
tegra-espimage-jetson-orin-nano-devkit-20240523185806.rootfs.esp
tegra-espimage-jetson-orin-nano-devkit-20240523185806.rootfs.manifest
tegra-espimage-jetson-orin-nano-devkit-20240523185806.testdata.json
tegra-espimage-jetson-orin-nano-devkit.esp
tegra-espimage-jetson-orin-nano-devkit.manifest
tegra-espimage-jetson-orin-nano-devkit.testdata.json
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit-20240523185806.rootfs.cpio.gz.cboot
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit-20240523185806.rootfs.manifest
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit-20240523185806.testdata.json
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit.cboot
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit.cpio.gz.cboot
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit.manifest
tegra-initrd-flash-initramfs-jetson-orin-nano-devkit.testdata.json
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.bl_only.bup-payload
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.kernel_only.bup-payload
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.rootfs.cpio.gz
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.rootfs.cpio.gz.cboot
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.rootfs.manifest
tegra-minimal-initramfs-jetson-orin-nano-devkit-20240523185806.testdata.json
tegra-minimal-initramfs-jetson-orin-nano-devkit.bl_only.bup-payload
tegra-minimal-initramfs-jetson-orin-nano-devkit.cboot
tegra-minimal-initramfs-jetson-orin-nano-devkit.cpio.gz
tegra-minimal-initramfs-jetson-orin-nano-devkit.cpio.gz.cboot
tegra-minimal-initramfs-jetson-orin-nano-devkit.kernel_only.bup-payload
tegra-minimal-initramfs-jetson-orin-nano-devkit.manifest
tegra-minimal-initramfs-jetson-orin-nano-devkit.testdata.json
tos-jetson-orin-nano-devkit-35.5.0-r0.img
tos-jetson-orin-nano-devkit.img
uefi_jetson.bin

```

Deploy.sh script:
```
#!/bin/bash

image=$1
machine=$2

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
deployfile=${image}-${machine}.tegraflash.tar.gz
tmpdir=`mktemp`

rm -rf $tmpdir
mkdir -p $tmpdir
echo "Using temp directory $tmpdir"
pushd $tmpdir
cp $scriptdir/build/tmp-glibc/deploy/images/${machine}/$deployfile .
tar -xvf $deployfile
set -e
sudo ./doflash.sh
popd
echo "Removing temp directory $tmpdir"
rm -rf $tmpdir
```

Command to deploy:
```
# /work/yocto-meta-ros$ sudo ./deploy.sh ros-image-core-humble jetson-orin-nano-devkit
Using temp directory /tmp/tmp.I2tOTAStfC
/tmp/tmp.I2tOTAStfC /work/yocto-meta-ros
./
tegra234-mb1-bct-p3701-0005-rc05-204mhz.dtsi
tegrasign_v3_hsm.py
tegra234-mb1-bct-gpio-p3701-0002-P3711-0000.dtsi
tegra234-mb1-bct-misc-p3701-0008-p3740-0002.dts
tegra234-p3701-0005-wb0sdram-l4t.dts
tegra234-mb1-bct-p3701-0005-as-p3767-0004-rc06-204mhz.dtsi
tegra234-mb1-bct-p3701-0005-as-p3767-0000-rc09-204mhz.dtsi
tegra234-mb1-bct-gpio-p3701-0002-p3740-0002.dtsi
tegraparser_v2
tegra234-mb1-bct-p3767-0000-rc12-204mhz.dtsi
tegra234-mb1-bct-p3701-0005-rc03-665mhz.dtsi
tegra234-mb1-bct-p3701-0002-p3740-0002-sdram-32gb-Micron-lpddr5-204MHz-bct-ecc-encr.dtsi
tegra234-mb1-bct-p3767-0004-rc13-204mhz.dtsi
tegra234-mb1-bct-p3701-0000-rc07-665mhz.dtsi
tegra234-bpmp-3701-0000-3737-0000-maxn.dtb
tegra234-bpmp-3701-0008-3737-0000.dtb
tegrabct_v2
L4TConfiguration.dtbo
tegra234-p3701-0000-sdram.dtsi
tegra234-mb1-bct-uphy-lanes-p3701-0002-p3711-0000.dts
tegra234-mb1-bct-p3701-0005-rc09-665mhz.dtsi
tegrabl_carveout_id.h
tegra234-mb1-bct-prod-p3701-0000.dts
tegra234-mb1-bct-uphylane-si-c7x2.dtsi
tegra234-mb1-bct-reset-p3701-0002-p3740-0002.dts
tegra234-mb1-bct-p3767-0004-rc06-665mhz.dtsi
...
Welcome to Tegra Flash
version 1.0.0
Type ? or help for help and q or quit to exit
Use ! to execute system commands
 
[   0.0421 ] tegrarcm_v2 --chip 0x23 0 --ismb2applet
[   0.0430 ] File rcm_state open failed
[   0.0434 ] ERROR: failed to read rcm_state
[   0.0434 ] 
[   0.0510 ] tegrasign_v3.py --key None --getmode mode.txt
[   0.0513 ] Assuming zero filled SBK key
[   0.0440 ] Pre-processing config: tegra234-mb1-bct-device-p3767-0000.dts
[   0.0502 ] Pre-processing config: tegra234-mb1-bct-misc-p3767-0000.dts
[   0.0599 ] Parsing partition layout
[   0.0612 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0629 ] Kernel DTB used: None
[   0.0629 ] WARNING: dce base dtb is not provided

[   0.0629 ] Parsing partition layout
[   0.0639 ] tegraparser_v2 --pt readinfo_t234_min_prod.xml.tmp
[   0.0650 ] Creating list of images to be signed
[   0.0658 ] tegrahost_v2 --chip 0x23 0 --partitionlayout readinfo_t234_min_prod.xml.bin --list images_list.xml zerosbk
[   0.0666 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
[   0.0679 ] Header already present for mb1_t234_prod_aligned_sigheader.bin
[   0.0683 ] MB1: Nvheader already present is mb1_t234_prod_aligned.bin
...
[   7.5578 ] Added binary blob_tegra234-bpmp-3767-0003-3509-a02_with_odm_sigheader.dtb.encrypt of size 199936
[   7.5587 ] Added binary blob_camera-rtcpu-sce_sigheader.img.encrypt of size 166304
[   7.5596 ] Added binary blob_camera-rtcpu-t234-rce_sigheader.img.encrypt of size 540000
[   7.5604 ] Added binary blob_adsp-fw_sigheader.bin.encrypt of size 400960
[   7.5611 ] Added binary blob_spe_t234_sigheader.bin.encrypt of size 270336
[   7.5617 ] Added binary blob_tos-optee_t234_sigheader.img.encrypt of size 1259424
[   7.5625 ] Added binary blob_eks_sigheader.img.encrypt of size 9232
[   7.5713 ] Sending membct and RCM blob
[   7.5727 ] tegrarcm_v2 --chip 0x23 0 --pollbl --download bct_mem mem_rcm_sigheader.bct.encrypt --download blob blob.bin
[   7.5736 ] BL: version 1.4.0.1-t234-54845784-08e631ca last_boot_error: 0
[   7.6016 ] Sending bct_mem
[   7.6456 ] Sending blob
[   9.0212 ] completed
[   9.0213 ] Retrieving storage infomation
[   9.0251 ] tegrarcm_v2 --chip 0x23 0 --oem platformdetails storage storage_info.bin
```

It hangs at the last line forever. I had to Ctrl+C to kill the flashing process. Any idea why it hangs?

**Comment by jinchenglee** [comment]
Forgot to mention, I was trying to flash the installed NVME ssd disk on the Orin Nano devkit. There's no sd card installed on the kit when the flashing was happening. 

Since no `*wic*` image were generated (which did got generated with rpi4 example in the[ kas README page](https://github.com/ros/meta-ros/tree/build/kas)), I assume the built image is not for sd card anyways.

**Comment by jinchenglee** [comment]
I see similar symptom, although not exactly the same, on [this page](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit#issues-during-flashing) about flashing meta-tegra generated image. I will try connecting serial debug to see what's going on there and get back here. Thanks.

**Comment by jinchenglee** [comment]
Ok, it turns out meta-ros/kas/oeros-kirkstone-humble-jetson-orin-nano-devkit.yml is by default for SD card image only. 

According to explanation [here](https://github.com/OE4T/meta-tegra/wiki/initrd-flashing-support#comparison-with-stock-l4t-initrd-flashing): 
`With OE builds, TNSPEC_BOOTDEV selection is performed at build time. Switching back and forth between external rootfs and internal storage should be done with different builds.`

To build an image for installed NVME ssd, I added below line to build/conf/local.conf:
```
MACHINE ??= "jetson-orin-nano-devkit-nvme"
```
and added these two files:
```
	kas/machine/jetson-orin-nano-devkit-nvme.yml
	kas/oeros-kirkstone-humble-jetson-orin-nano-devkit-nvme.yml

# :/work/yocto-meta-ros/meta-ros$ cat kas/machine/jetson-orin-nano-devkit-nvme.yml
header:
  version: 14

machine: "jetson-orin-nano-devkit-nvme"

repos:
  meta-tegra:
    url: "https://github.com/OE4T/meta-tegra.git"
    path: "layers/meta-tegra"

  meta-tegra-community:
    url: "https://github.com/OE4T/meta-tegra-community.git"
    path: "layers/meta-tegra-community"

  tegra-demo-distro:
    url: "https://github.com/OE4T/tegra-demo-distro.git"
    path: "layers/tegra-demo-distro"
    layers:
      layers/meta-tegrademo:
      layers/meta-tegra-support:

  virtualization:
    url: "https://git.yoctoproject.org/git/meta-virtualization"
    path: "layers/meta-virtualization"

local_conf_header:
  jetson-orin-nano-devkit: |
    # Set DISTRO_FEATURES to enable latent features in meta-virtualization
    DISTRO_FEATURES:append = " virtualization"
# :/work/yocto-meta-ros/meta-ros$ cat kas/oeros-kirkstone-humble-jetson-orin-nano-devkit-nvme.yml
header:
  version: 14
  includes:
    - yocto/kirkstone.yml
    - ros2/humble.yml
    - machine/jetson-orin-nano-devkit-nvme.yml
    - common.yml

```

Because in file 
```layers/meta-tegra/conf/machine/jetson-orin-nano-devkit-nvme.conf:TNSPEC_BOOTDEV ?= "nvme0n1p1"```, which means jetson-orin-nano-devkit-nvme defaults to boot from NVME disk.

Build with this command can generate right image to be flashed. 
```
kas build meta-ros/kas/oeros-kirkstone-humble-jetson-orin-nano-devkit-nvme.yml
```
