### ISSUE TITLE
{jazzy} Superflore Update for jazzy

### ISSUE THREAD

**Issue by jiaxshi** [ros/meta-ros#1222]
**Describe the bug**
Lots packages are missing in current meta-ros2-jazzy/generated-recipes since they are generated in 2024.4. Compared to latest distribution many packages are not included.
For example, navigation2 packages:
```
navigation2:
    doc:
      type: git
      url: https://github.com/ros-planning/navigation2.git
      version: jazzy
    release:
      packages:
      - costmap_queue
      - dwb_core
      - dwb_critics
      - dwb_msgs
      - dwb_plugins
      - nav2_amcl
      - nav2_behavior_tree
      - nav2_behaviors
      - nav2_bringup
      - nav2_bt_navigator
      - nav2_collision_monitor
      - nav2_common
      - nav2_constrained_smoother
      - nav2_controller
      - nav2_core
      - nav2_costmap_2d
      - nav2_dwb_controller
      - nav2_graceful_controller
      - nav2_lifecycle_manager
      - nav2_loopback_sim
      - nav2_map_server
      - nav2_mppi_controller
      - nav2_msgs
      - nav2_navfn_planner
      - nav2_planner
      - nav2_regulated_pure_pursuit_controller
      - nav2_rotation_shim_controller
      - nav2_rviz_plugins
      - nav2_simple_commander
      - nav2_smac_planner
      - nav2_smoother
      - nav2_system_tests
      - nav2_theta_star_planner
      - nav2_util
      - nav2_velocity_smoother
      - nav2_voxel_grid
      - nav2_waypoint_follower
      - nav_2d_msgs
      - nav_2d_utils
      - navigation2
      - opennav_docking
      - opennav_docking_bt
      - opennav_docking_core
```
